name: Publish Package

on:
    push:
        # Optionally, you can trigger on tags like v1.0.0
        tags:
            - 'v*.*.*'
        branches:
            - master

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  registry-url: 'https://registry.npmjs.org/'
                  node-version: '20'

            - name: Install Bun
              run: |
                  curl -fsSL https://bun.sh/install | bash
                  # Optionally, add bun to PATH for the rest of the job:
                  echo "$HOME/.bun/bin" >> $GITHUB_PATH

            - name: Install dependencies with Bun
              run: bun install

            - name: Check Lint
              run: bun run lint:check

            - name: Test the project
              run: bun run test:coverage

            - name: Build the project
              run: bun run build

            - name: Publish to npm
              run: bun publish
              env:
                  NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
